# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('polygon', models.CharField(default='POLYGON((0.0), (0.0), (0.0))', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='json_rest_api.Provider'),
        ),
    ]
